# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd8b54cba9dfe077a41b5a342152e0649b73c129fc68d2f2e9b2ea072d9ec7dd09e29b0234c5d0a7e4f266c51b3dbfdb5422c643f3948e97aca4fa8f05039583

test:
  secret_key_base: 45ba967fb5ce08af83e9c13c9734ab65d946f4f4a227eceb9d849cc47d1b242655db71e2b8d3c8b3f142534f52060d73270184b8cd111c54d6355edaff416f96

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
